# Generated by Django 3.2.9 on 2021-11-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='O nome do aluno.', max_length=100, verbose_name='nome')),
                ('cpf', models.CharField(help_text='O número de CPF do aluno.', max_length=11, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
            },
        ),
    ]
