# Generated by Django 3.2.9 on 2021-11-12 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_campos_adicionais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='registro_aluno',
            field=models.CharField(blank=True, help_text='O número de registro interno do aluno, e.g. X00000-0.', max_length=10, null=True, validators=[django.core.validators.RegexValidator('[A-Z][0-9]{5}-[0-9]')], verbose_name='registro de aluno'),
        ),
    ]
