# Generated by Django 3.2.9 on 2021-11-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='O nome do cliente.', max_length=100, verbose_name='nome')),
                ('telefone', models.CharField(help_text='O telefone do cliente.', max_length=20, verbose_name='telefone')),
                ('idade', models.SmallIntegerField(help_text='A idade do cliente.', verbose_name='idade')),
                ('profissao', models.CharField(help_text='A profissão do cliente.', max_length=100, verbose_name='profissão')),
                ('email', models.EmailField(help_text='O email do cliente.', max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
    ]
